version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - opa
    networks:
      - app-network

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command: 
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies"
    volumes:
      - ./policies:/policies:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge