version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./lua:/etc/nginx/lua:ro
    depends_on:
      - app
      - opa
    networks:
      - app-network

  app:
    build: 
      context: ../../
      dockerfile: examples/nginx/Dockerfile
    expose:
      - "8000"
    depends_on:
      - opa
    networks:
      - app-network

  opa:
    image: openpolicyagent/opa:latest
    expose:
      - "8181"
    command: 
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies"
    volumes:
      - ../../policies:/policies:ro
    networks:
      - app-network

  # Request counter for rate limiting (Redis)
  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge